import {
  Account,
  Category,
  Debt,
  RecurringRule,
  Transaction,
  UserSettings,
  Vault,
} from "../types";

export const SEED_CATEGORIES: Category[] = [
  { id: "cat_food", name: "Food & Dining", icon: "Utensils", color: "#00F0FF", type: "expense", order: 0, isDefault: true },
  { id: "cat_tech", name: "Tech & Infrastructure", icon: "Cpu", color: "#FF5C00", type: "expense", order: 1, isDefault: true },
  { id: "cat_subs", name: "Subscriptions & SaaS", icon: "Repeat", color: "#FFB800", type: "expense", order: 2, isDefault: true },
  { id: "cat_trans", name: "Transport & Mobility", icon: "Navigation", color: "#00FF88", type: "expense", order: 3, isDefault: true },
  { id: "cat_util", name: "Housing & Utilities", icon: "Home", color: "#9D00FF", type: "expense", order: 4, isDefault: true },
  { id: "cat_health", name: "Health & Fitness", icon: "Activity", color: "#FF0055", type: "expense", order: 5, isDefault: true },
  { id: "cat_ent", name: "Entertainment & Cyber", icon: "Gamepad2", color: "#00E5FF", type: "expense", order: 6, isDefault: true },
  { id: "cat_income", name: "Primary Income", icon: "TrendingUp", color: "#00FF88", type: "income", order: 0, isDefault: true },
  { id: "cat_bonus", name: "Syndicate / Consulting", icon: "Coins", color: "#FFB800", type: "income", order: 1, isDefault: true },
  { id: "cat_transfer", name: "Internal Transfer", icon: "ArrowLeftRight", color: "#708090", type: "expense", order: 7, isDefault: true },
  { id: "cat_debt", name: "Debt Settlement", icon: "Handshake", color: "#E056FD", type: "expense", order: 8, isDefault: true },
];

export const SEED_ACCOUNTS: Account[] = [
  {
    id: "acc_bca",
    name: "BCA Priority",
    type: "checking",
    currency: "IDR",
    initialBalance: 42500000,
    currentBalance: 42500000,
    color: "#00F0FF",
    icon: "Landmark",
    isArchived: false,
    order: 0,
  },
  {
    id: "acc_mandiri",
    name: "Mandiri Wealth",
    type: "savings",
    currency: "IDR",
    initialBalance: 85000000,
    currentBalance: 85000000,
    color: "#00FF88",
    icon: "Building2",
    isArchived: false,
    order: 1,
  },
  {
    id: "acc_tokyo_cc",
    name: "Tokyo Black Platinum CC",
    type: "credit",
    currency: "IDR",
    initialBalance: 0,
    currentBalance: -4250000,
    color: "#FF5C00",
    icon: "CreditCard",
    isArchived: false,
    creditLimit: 50000000,
    statementClosingDay: 20,
    order: 2,
  },
  {
    id: "acc_gopay",
    name: "GoPay / Cyberia Wallet",
    type: "ewallet",
    currency: "IDR",
    initialBalance: 1250000,
    currentBalance: 1250000,
    color: "#00F0FF",
    icon: "Smartphone",
    isArchived: false,
    order: 3,
  },
  {
    id: "acc_cash_stash",
    name: "Physical Cash Stash",
    type: "cash",
    currency: "IDR",
    initialBalance: 3500000,
    currentBalance: 3500000,
    color: "#FFB800",
    icon: "Banknote",
    isArchived: false,
    order: 4,
  },
];

export const SEED_VAULTS: Vault[] = [
  {
    id: "vault_gear",
    title: "Shibuya Tech Lab Gear",
    targetAmount: 25000000,
    currentAmount: 18500000,
    assignedAccountId: "acc_bca",
    color: "#00F0FF",
    icon: "Cpu",
    status: "active",
    targetDate: "2026-12-31",
    order: 0,
  },
  {
    id: "vault_emergency",
    title: "Emergency Runway (6 Months)",
    targetAmount: 90000000,
    currentAmount: 75000000,
    assignedAccountId: "acc_mandiri",
    color: "#00FF88",
    icon: "ShieldAlert",
    status: "active",
    order: 1,
  },
  {
    id: "vault_retreat",
    title: "Kyoto Ryokan Retreat",
    targetAmount: 15000000,
    currentAmount: 15000000,
    assignedAccountId: "acc_bca",
    color: "#FF5C00",
    icon: "Mountain",
    status: "reached",
    targetDate: "2026-10-15",
    order: 2,
  },
];

export const SEED_DEBTS: Debt[] = [
  {
    id: "debt_akira",
    counterparty: "Akira Sato",
    amount: 1500000,
    paidAmount: 500000,
    direction: "owed", // He owes us
    desc: "Modular Synthesizer Group Order",
    status: "active",
    dueDate: "2026-09-25",
    repaymentHistory: [
      {
        transactionId: "tx_init_repay_1",
        amount: 500000,
        date: "2026-08-28",
        accountId: "acc_bca",
      },
    ],
    createdAt: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "debt_cyberia",
    counterparty: "Cyberia Node Cluster",
    amount: 850000,
    paidAmount: 0,
    direction: "owe", // We owe
    desc: "Dedicated GPU Node Invoice (Unsettled)",
    status: "active",
    dueDate: "2026-09-15",
    repaymentHistory: [],
    createdAt: "2026-09-01T08:00:00.000Z",
  },
];

export const SEED_RECURRING: RecurringRule[] = [
  {
    id: "rec_syndicate",
    title: "Syndicate Retainer Payout",
    amount: 32000000,
    type: "income",
    categoryId: "cat_income",
    accountId: "acc_bca",
    frequency: "monthly",
    interval: 1,
    startDate: "2026-01-01",
    nextRunDate: "2026-10-01",
    autoExecute: true,
  },
  {
    id: "rec_fiber",
    title: "Fiber Optic 1Gbps Dedicated",
    amount: 750000,
    type: "expense",
    categoryId: "cat_util",
    accountId: "acc_bca",
    frequency: "monthly",
    interval: 1,
    startDate: "2026-01-05",
    nextRunDate: "2026-09-05",
    autoExecute: true,
  },
  {
    id: "rec_ai_api",
    title: "OpenAI / Anthropic Inference API",
    amount: 1450000,
    type: "expense",
    categoryId: "cat_subs",
    accountId: "acc_tokyo_cc",
    frequency: "monthly",
    interval: 1,
    startDate: "2026-02-12",
    nextRunDate: "2026-09-12",
    autoExecute: false,
  },
  {
    id: "rec_figma",
    title: "Figma Enterprise Seat",
    amount: 280000,
    type: "expense",
    categoryId: "cat_subs",
    accountId: "acc_tokyo_cc",
    frequency: "monthly",
    interval: 1,
    startDate: "2026-03-01",
    nextRunDate: "2026-09-18",
    autoExecute: true,
  },
];

export const FACTORY_BASELINE_ACCOUNTS: Account[] = [
  {
    id: "acc_checking",
    name: "Primary Bank Account",
    type: "checking",
    currency: "IDR",
    initialBalance: 0,
    currentBalance: 0,
    color: "#00F0FF",
    icon: "Landmark",
    isArchived: false,
    order: 0,
  },
  {
    id: "acc_cash",
    name: "Cash Wallet",
    type: "cash",
    currency: "IDR",
    initialBalance: 0,
    currentBalance: 0,
    color: "#94A3B8",
    icon: "Banknote",
    isArchived: false,
    order: 1,
  },
];

export const SEED_SETTINGS: UserSettings = {
  currency: "IDR",
  locale: "id-ID",
  monthlyBudget: 18000000,
  categoryBudgets: {
    cat_food: 4500000,
    cat_tech: 4000000,
    cat_subs: 2500000,
    cat_trans: 2000000,
    cat_util: 3000000,
    cat_ent: 2000000,
  },
  theme: "tokyo-slate",
  privacyMode: false,
  hapticFeedback: true,
  soundEnabled: true,
  companionApiKey: "fos_sec_79a83f120e89b41a9c472d001",
  security: {
    // Salted SHA-256 for fallback PIN "0000" with salt "d9e8f7a6b5c43210"
    pinHash: "46d0a79051876a4ee04d20912f2ea4cc3b94200632d433be54ca0df82ea243c3",
    pinSalt: "d9e8f7a6b5c43210",
    isPinSet: false, // Indicates fallback "0000" is active
    autoLockTimeoutMinutes: 5,
    biometricsEnabled: false,
    lastUnlockedAt: Date.now(),
  },
};

// Generates dynamic seed transactions for current month and prior days
export function generateSeedTransactions(): Transaction[] {
  const txs: Transaction[] = [
    {
      id: "tx_inc_1",
      desc: "Syndicate Engineering Retainer",
      amount: 32000000,
      type: "income",
      categoryId: "cat_income",
      fromAccountId: "acc_bca",
      tags: ["Syndicate", "TaxReportable"],
      date: "2026-09-01",
      time: "09:00",
      source: "web_client",
      createdAt: "2026-09-01T09:00:00.000Z",
      updatedAt: "2026-09-01T09:00:00.000Z",
    },
    {
      id: "tx_exp_1",
      desc: "Cyberia Ramen Bar & Craft Brew",
      amount: 185000,
      type: "expense",
      categoryId: "cat_food",
      fromAccountId: "acc_ewallet",
      tags: ["Dining"],
      date: "2026-09-01",
      time: "12:30",
      source: "web_client",
      createdAt: "2026-09-01T12:30:00.000Z",
      updatedAt: "2026-09-01T12:30:00.000Z",
    },
    {
      id: "tx_exp_2",
      desc: "GitHub Enterprise Copilot Seat",
      amount: 340000,
      type: "expense",
      categoryId: "cat_subs",
      fromAccountId: "acc_tokyo_cc",
      tags: ["DevTools"],
      date: "2026-09-02",
      time: "14:15",
      source: "web_client",
      createdAt: "2026-09-02T14:15:00.000Z",
      updatedAt: "2026-09-02T14:15:00.000Z",
    },
    {
      id: "tx_exp_3",
      desc: "Express Commuter Train & Metro Pass",
      amount: 120000,
      type: "expense",
      categoryId: "cat_trans",
      fromAccountId: "acc_ewallet",
      tags: ["Commute"],
      date: "2026-09-02",
      time: "08:45",
      source: "pwa_quick_action",
      createdAt: "2026-09-02T08:45:00.000Z",
      updatedAt: "2026-09-02T08:45:00.000Z",
    },
    {
      id: "tx_vault_1",
      desc: "Monthly Reserve Stash -> Shibuya Tech Gear",
      amount: 2500000,
      type: "vault_deposit",
      categoryId: "cat_transfer",
      fromAccountId: "acc_bca",
      vaultId: "vault_gear",
      tags: ["SavingsGoal"],
      date: "2026-09-02",
      time: "18:00",
      source: "web_client",
      createdAt: "2026-09-02T18:00:00.000Z",
      updatedAt: "2026-09-02T18:00:00.000Z",
    },
    {
      id: "tx_exp_4",
      desc: "Specialty Espresso Bar Shot",
      amount: 65000,
      type: "expense",
      categoryId: "cat_food",
      fromAccountId: "acc_cash",
      tags: ["Coffee"],
      date: "2026-09-03",
      time: "09:30",
      source: "pwa_quick_action",
      createdAt: "2026-09-03T09:30:00.000Z",
      updatedAt: "2026-09-03T09:30:00.000Z",
    },
    {
      id: "tx_exp_5",
      desc: "Mechanical Keycap Set (Industrial Dye-Sub)",
      amount: 950000,
      type: "expense",
      categoryId: "cat_tech",
      fromAccountId: "acc_tokyo_cc",
      tags: ["Hardware"],
      date: "2026-09-03",
      time: "11:00",
      source: "web_client",
      createdAt: "2026-09-03T11:00:00.000Z",
      updatedAt: "2026-09-03T11:00:00.000Z",
    },
  ];

  // Also add some prior month transactions for runway & trailing calculation
  for (let day = 1; day <= 28; day += 3) {
    const dStr = `2026-08-${String(day).padStart(2, "0")}`;
    txs.push({
      id: `tx_hist_aug_${day}`,
      desc: day % 2 === 0 ? "Tokyo Metro Transit" : "Cyber Food Market",
      amount: 150000 + (day * 12000),
      type: "expense",
      categoryId: day % 2 === 0 ? "cat_trans" : "cat_food",
      fromAccountId: "acc_ewallet",
      tags: ["Historical"],
      date: dStr,
      time: "12:00",
      source: "web_client",
      createdAt: `${dStr}T12:00:00.000Z`,
      updatedAt: `${dStr}T12:00:00.000Z`,
    });
  }

  return txs;
}
